paths:
  preprocess: /users/rushworth/gwr089/scratch/Generalization-Preprocess
  reconstructed: /well/rushworth/projects/nhp/users/simone/raw/reconstructed
  prepared: /users/rushworth/gwr089/scratch/Generalization-Preprocess/prepared/output
  struct: /well/rushworth/projects/nhp/users/simone/struct
  zach: /users/rushworth/gwr089/scratch/Generalization-Preprocess/zach
  zeno: /users/rushworth/gwr089/scratch/Generalization-Preprocess/zeno

zach:
  task1: [MI01049P, MI01051P, MI01060P, MI01062P, MI01063P, MI01108P, MI01111P, MI01115P, MI01118P, MI01130P, MI01132P, MI01134P, MI01136P]
  task2: [MI01140P, MI01142P, MI01144P, MI01150P, MI01159P, MI01162P, MI01167P]
  task3: [MI01170P, MI01197P, MI01204P, MI01206P, MI01211P, MI01216P, MI01221P]
  task4: [MI01227P, MI01230P, MI01232P, MI01236P, MI01241P, MI01246P, MI01249P]
  task5: [MI01253P, MI01255P, MI01262P]
